import type { Vehicle } from './types';

export const mockVehicles: Vehicle[] = [
  {
    id: 'V001',
    name: 'Cargo King 1',
    type: 'Truck',
    latitude: 34.0522,
    longitude: -118.2437,
    speed: 65,
    heading: 45,
    fuelConsumption: 25.5,
    status: 'Moving',
  },
  {
    id: 'V002',
    name: 'City Sprinter',
    type: 'Van',
    latitude: 34.055,
    longitude: -118.25,
    speed: 0,
    heading: 180,
    fuelConsumption: 12.1,
    status: 'Idle',
  },
  {
    id: 'V003',
    name: 'Metro Mover',
    type: 'Van',
    latitude: 34.048,
    longitude: -118.245,
    speed: 40,
    heading: 270,
    fuelConsumption: 13.2,
    status: 'Moving',
  },
  {
    id: 'V004',
    name: 'ExecuRide 5',
    type: 'Car',
    latitude: 34.06,
    longitude: -118.26,
    speed: 80,
    heading: 90,
    fuelConsumption: 8.5,
    status: 'Moving',
  },
  {
    id: 'V005',
    name: 'Hauler Prime',
    type: 'Truck',
    latitude: 34.04,
    longitude: -118.23,
    speed: 0,
    heading: 0,
    fuelConsumption: 0,
    status: 'Offline',
  },
];
